name: Auto-Update Toolbox Version

on:
  repository_dispatch:
    types: [genai-toolbox-update]

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Update version in file
        run: |
          NEW_VERSION=${{ github.event.client_payload.new_version }}
          # Remove the 'v' prefix from the version tag
          NEW_VERSION_CLEAN=$(echo "$NEW_VERSION" | sed 's/^v//')
          
          # Update the single integration.cloudbuild.yaml file for toolbox-core
          sed -i "s/_TOOLBOX_VERSION: '.*/_TOOLBOX_VERSION: '$NEW_VERSION_CLEAN'/" packages/toolbox-core/integration.cloudbuild.yaml
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6
        with:
          commit-message: 'chore(deps): update genai-toolbox version to ${{ github.event.client_payload.new_version }}'
          title: 'chore(deps): update genai-toolbox version to ${{ github.event.client_payload.new_version }}'
          body: 'This PR was automatically generated to update the _TOOLBOX_VERSION to ${{ github.event.client_payload.new_version }}.'
          branch: auto-update/js-toolbox-version
